name: Build

on:
  push:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.10.0"
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn build
