name: Deploy to Cloudflare Pages

on:
  workflow_run:
    workflows: ["Conventional Commits"]
    types:
      - completed

jobs:
  deploy-to-cloudflare:
    name: Deploy to Cloudflare Pages
    runs-on: ubuntu-22.04
    permissions:
      contents: read

    steps:
      - name: Deploy to Cloudflare
        uses: ubiquity/cloudflare-deploy-action@main
        with:
          cloudflare_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          supabase_url: ${{ secrets.SUPABASE_URL }}
          supabase_key: ${{ secrets.SUPABASE_KEY }}
          repository: ${{ github.repository }}
          production_branch: "development"
          output_directory: "static"
