name: Deploy to Cloudflare Pages

on:
  push:
  pull_request:
    types: [closed]

jobs:
  deploy-to-cloudflare:
    name: Deploy to Cloudflare Pages
    # Only push and merged pull request events
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    runs-on: ubuntu-22.04
    permissions:
      contents: read

    steps:
      - name: Deploy to Cloudflare
        uses: ubiquity/cloudflare-deploy-action@main
        with:
          cloudflare_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          repository: ${{ github.repository }}
          production_branch: ${{ github.event.repository.default_branch }}
          output_directory: "static"
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
